-- seed_stage_configs.sql
-- 64 個主線關卡配置（8 章 × 8 關）
-- 使用 wrangler d1 execute globalganlan-db --remote --file=scripts/seed_stage_configs.sql

DELETE FROM stage_configs;

-- ═══════════════════════════════════════════════════════════
-- 第 1 章 🏙️ 廢墟之城
-- ═══════════════════════════════════════════════════════════

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('1-1', 1, 1, '[{"heroId":1,"slot":1,"levelMultiplier":1,"hpMultiplier":0.06,"atkMultiplier":0.04,"defMultiplier":0.04,"speedMultiplier":0.6}]', '{"exp":45,"gold":80,"diamond":0}', '{"chapterName":"🏙️ 廢墟之城","stageName":"城市入口","description":"傾斜的路牌指向死寂的高樓群","bgTheme":"city","difficulty":1,"recommendedLevel":1,"isBoss":false,"chapterIcon":"🏙️"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('1-2', 1, 2, '[{"heroId":1,"slot":1,"levelMultiplier":1,"hpMultiplier":0.08,"atkMultiplier":0.05,"defMultiplier":0.05,"speedMultiplier":0.6},{"heroId":2,"slot":2,"levelMultiplier":1,"hpMultiplier":0.08,"atkMultiplier":0.05,"defMultiplier":0.05,"speedMultiplier":0.6}]', '{"exp":57,"gold":98,"diamond":0}', '{"chapterName":"🏙️ 廢墟之城","stageName":"廢棄商場","description":"散落的購物車間迴盪著低沉嘶吼","bgTheme":"city","difficulty":2,"recommendedLevel":2,"isBoss":false,"chapterIcon":"🏙️"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('1-3', 1, 3, '[{"heroId":1,"slot":1,"levelMultiplier":1,"hpMultiplier":0.20,"atkMultiplier":0.15,"defMultiplier":0.15,"speedMultiplier":0.9},{"heroId":2,"slot":2,"levelMultiplier":1,"hpMultiplier":0.20,"atkMultiplier":0.15,"defMultiplier":0.15,"speedMultiplier":0.9}]', '{"exp":69,"gold":116,"diamond":0}', '{"chapterName":"🏙️ 廢墟之城","stageName":"地下車庫","description":"暗處的車輛間閃爍著不明光源","bgTheme":"city","difficulty":3,"recommendedLevel":3,"isBoss":false,"chapterIcon":"🏙️"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('1-4', 1, 4, '[{"heroId":1,"slot":1,"levelMultiplier":1,"hpMultiplier":0.25,"atkMultiplier":0.18,"defMultiplier":0.18,"speedMultiplier":0.9},{"heroId":2,"slot":2,"levelMultiplier":1,"hpMultiplier":0.25,"atkMultiplier":0.18,"defMultiplier":0.18,"speedMultiplier":0.9}]', '{"exp":81,"gold":133,"diamond":0}', '{"chapterName":"🏙️ 廢墟之城","stageName":"斷橋殘垣","description":"斷裂的橋面下是無底的深淵","bgTheme":"city","difficulty":4,"recommendedLevel":4,"isBoss":false,"chapterIcon":"🏙️"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('1-5', 1, 5, '[{"heroId":1,"slot":1,"levelMultiplier":1,"hpMultiplier":0.30,"atkMultiplier":0.22,"defMultiplier":0.22,"speedMultiplier":1},{"heroId":2,"slot":2,"levelMultiplier":1,"hpMultiplier":0.30,"atkMultiplier":0.22,"defMultiplier":0.22,"speedMultiplier":1},{"heroId":3,"slot":3,"levelMultiplier":1,"hpMultiplier":0.30,"atkMultiplier":0.22,"defMultiplier":0.22,"speedMultiplier":1}]', '{"exp":93,"gold":151,"diamond":0}', '{"chapterName":"🏙️ 廢墟之城","stageName":"醫院廢墟","description":"沾血的病床上仍有掙扎的痕跡","bgTheme":"city","difficulty":5,"recommendedLevel":6,"isBoss":false,"chapterIcon":"🏙️"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('1-6', 1, 6, '[{"heroId":1,"slot":1,"levelMultiplier":1,"hpMultiplier":0.35,"atkMultiplier":0.25,"defMultiplier":0.25,"speedMultiplier":1},{"heroId":2,"slot":2,"levelMultiplier":1,"hpMultiplier":0.35,"atkMultiplier":0.25,"defMultiplier":0.25,"speedMultiplier":1},{"heroId":3,"slot":3,"levelMultiplier":1,"hpMultiplier":0.35,"atkMultiplier":0.25,"defMultiplier":0.25,"speedMultiplier":1}]', '{"exp":105,"gold":169,"diamond":0}', '{"chapterName":"🏙️ 廢墟之城","stageName":"警察局","description":"破碎的警車燈還在無力地閃爍","bgTheme":"city","difficulty":6,"recommendedLevel":7,"isBoss":false,"chapterIcon":"🏙️"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('1-7', 1, 7, '[{"heroId":1,"slot":1,"levelMultiplier":1,"hpMultiplier":0.40,"atkMultiplier":0.30,"defMultiplier":0.30,"speedMultiplier":1},{"heroId":2,"slot":2,"levelMultiplier":1,"hpMultiplier":0.40,"atkMultiplier":0.30,"defMultiplier":0.30,"speedMultiplier":1},{"heroId":3,"slot":3,"levelMultiplier":1,"hpMultiplier":0.40,"atkMultiplier":0.30,"defMultiplier":0.30,"speedMultiplier":1}]', '{"exp":117,"gold":187,"diamond":0}', '{"chapterName":"🏙️ 廢墟之城","stageName":"市政廳","description":"政府公告牆上爬滿了黑色菌絲","bgTheme":"city","difficulty":7,"recommendedLevel":8,"isBoss":false,"chapterIcon":"🏙️"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('1-8', 1, 8, '[{"heroId":1,"slot":1,"levelMultiplier":1,"hpMultiplier":0.45,"atkMultiplier":0.33,"defMultiplier":0.33,"speedMultiplier":1},{"heroId":2,"slot":2,"levelMultiplier":1,"hpMultiplier":0.45,"atkMultiplier":0.33,"defMultiplier":0.33,"speedMultiplier":1},{"heroId":3,"slot":3,"levelMultiplier":1,"hpMultiplier":0.70,"atkMultiplier":0.50,"defMultiplier":0.50,"speedMultiplier":0.9}]', '{"exp":129,"gold":204,"diamond":20,"items":[{"itemId":"chest_bronze","quantity":1,"dropRate":1}]}', '{"chapterName":"🏙️ 廢墟之城","stageName":"鐘樓之巔","description":"巨大鐘擺下潛伏著城市的主宰","bgTheme":"city","difficulty":8,"recommendedLevel":10,"isBoss":true,"chapterIcon":"🏙️"}');

-- ═══════════════════════════════════════════════════════════
-- 第 2 章 🌲 暗夜森林
-- ═══════════════════════════════════════════════════════════

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('2-1', 2, 1, '[{"heroId":2,"slot":1,"levelMultiplier":1,"hpMultiplier":0.7,"atkMultiplier":0.5,"defMultiplier":0.5,"speedMultiplier":1.07},{"heroId":3,"slot":2,"levelMultiplier":1,"hpMultiplier":0.7,"atkMultiplier":0.5,"defMultiplier":0.5,"speedMultiplier":1.07}]', '{"exp":141,"gold":222,"diamond":0}', '{"chapterName":"🌲 暗夜森林","stageName":"森林邊緣","description":"枯萎的樹木在夜風中發出呻吟","bgTheme":"forest","difficulty":9,"recommendedLevel":11,"isBoss":false,"chapterIcon":"🌲"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('2-2', 2, 2, '[{"heroId":2,"slot":1,"levelMultiplier":1,"hpMultiplier":0.77,"atkMultiplier":0.54,"defMultiplier":0.54,"speedMultiplier":1.07},{"heroId":3,"slot":2,"levelMultiplier":1,"hpMultiplier":0.77,"atkMultiplier":0.54,"defMultiplier":0.54,"speedMultiplier":1.07},{"heroId":4,"slot":3,"levelMultiplier":1,"hpMultiplier":0.77,"atkMultiplier":0.54,"defMultiplier":0.54,"speedMultiplier":1.07}]', '{"exp":153,"gold":240,"diamond":0}', '{"chapterName":"🌲 暗夜森林","stageName":"毒沼濕地","description":"冒泡的沼澤散發刺鼻的腐臭","bgTheme":"forest","difficulty":10,"recommendedLevel":12,"isBoss":false,"chapterIcon":"🌲"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('2-3', 2, 3, '[{"heroId":2,"slot":1,"levelMultiplier":1,"hpMultiplier":0.84,"atkMultiplier":0.59,"defMultiplier":0.59,"speedMultiplier":1.07},{"heroId":3,"slot":2,"levelMultiplier":1,"hpMultiplier":0.84,"atkMultiplier":0.59,"defMultiplier":0.59,"speedMultiplier":1.07},{"heroId":4,"slot":3,"levelMultiplier":1,"hpMultiplier":0.84,"atkMultiplier":0.59,"defMultiplier":0.59,"speedMultiplier":1.07}]', '{"exp":165,"gold":258,"diamond":0}', '{"chapterName":"🌲 暗夜森林","stageName":"蟲巢洞穴","description":"密密麻麻的蟲卵佈滿洞穴壁面","bgTheme":"forest","difficulty":11,"recommendedLevel":13,"isBoss":false,"chapterIcon":"🌲"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('2-4', 2, 4, '[{"heroId":2,"slot":1,"levelMultiplier":1,"hpMultiplier":0.91,"atkMultiplier":0.63,"defMultiplier":0.63,"speedMultiplier":1.07},{"heroId":3,"slot":2,"levelMultiplier":1,"hpMultiplier":0.91,"atkMultiplier":0.63,"defMultiplier":0.63,"speedMultiplier":1.07},{"heroId":4,"slot":3,"levelMultiplier":1,"hpMultiplier":0.91,"atkMultiplier":0.63,"defMultiplier":0.63,"speedMultiplier":1.07}]', '{"exp":177,"gold":276,"diamond":0}', '{"chapterName":"🌲 暗夜森林","stageName":"古老神木","description":"千年神木的根部纏繞著白骨","bgTheme":"forest","difficulty":12,"recommendedLevel":14,"isBoss":false,"chapterIcon":"🌲"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('2-5', 2, 5, '[{"heroId":2,"slot":1,"levelMultiplier":1,"hpMultiplier":0.99,"atkMultiplier":0.67,"defMultiplier":0.67,"speedMultiplier":1.07},{"heroId":3,"slot":2,"levelMultiplier":1,"hpMultiplier":0.99,"atkMultiplier":0.67,"defMultiplier":0.67,"speedMultiplier":1.07},{"heroId":4,"slot":3,"levelMultiplier":1,"hpMultiplier":0.99,"atkMultiplier":0.67,"defMultiplier":0.67,"speedMultiplier":1.07}]', '{"exp":189,"gold":293,"diamond":0}', '{"chapterName":"🌲 暗夜森林","stageName":"迷霧深處","description":"伸手不見五指的濃霧吞噬一切","bgTheme":"forest","difficulty":13,"recommendedLevel":16,"isBoss":false,"chapterIcon":"🌲"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('2-6', 2, 6, '[{"heroId":2,"slot":1,"levelMultiplier":1,"hpMultiplier":1.06,"atkMultiplier":0.71,"defMultiplier":0.71,"speedMultiplier":1.07},{"heroId":3,"slot":2,"levelMultiplier":1,"hpMultiplier":1.06,"atkMultiplier":0.71,"defMultiplier":0.71,"speedMultiplier":1.07},{"heroId":4,"slot":3,"levelMultiplier":1,"hpMultiplier":1.06,"atkMultiplier":0.71,"defMultiplier":0.71,"speedMultiplier":1.07}]', '{"exp":201,"gold":311,"diamond":0}', '{"chapterName":"🌲 暗夜森林","stageName":"狼嚎峽谷","description":"峽谷中的嚎叫不知是狼還是人","bgTheme":"forest","difficulty":14,"recommendedLevel":17,"isBoss":false,"chapterIcon":"🌲"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('2-7', 2, 7, '[{"heroId":2,"slot":1,"levelMultiplier":1,"hpMultiplier":1.13,"atkMultiplier":0.76,"defMultiplier":0.76,"speedMultiplier":1.07},{"heroId":3,"slot":2,"levelMultiplier":1,"hpMultiplier":1.13,"atkMultiplier":0.76,"defMultiplier":0.76,"speedMultiplier":1.07},{"heroId":4,"slot":3,"levelMultiplier":1,"hpMultiplier":1.13,"atkMultiplier":0.76,"defMultiplier":0.76,"speedMultiplier":1.07}]', '{"exp":213,"gold":329,"diamond":0}', '{"chapterName":"🌲 暗夜森林","stageName":"廢棄營地","description":"帳篷裡的日記停在末日那一天","bgTheme":"forest","difficulty":15,"recommendedLevel":18,"isBoss":false,"chapterIcon":"🌲"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('2-8', 2, 8, '[{"heroId":2,"slot":1,"levelMultiplier":1,"hpMultiplier":1.2,"atkMultiplier":0.8,"defMultiplier":0.8,"speedMultiplier":1.07},{"heroId":3,"slot":2,"levelMultiplier":1,"hpMultiplier":1.2,"atkMultiplier":0.8,"defMultiplier":0.8,"speedMultiplier":1.07},{"heroId":4,"slot":3,"levelMultiplier":1,"hpMultiplier":1.2,"atkMultiplier":0.8,"defMultiplier":0.8,"speedMultiplier":1.07},{"heroId":5,"slot":4,"levelMultiplier":1,"hpMultiplier":1.8,"atkMultiplier":1.2,"defMultiplier":1.2,"speedMultiplier":0.96}]', '{"exp":225,"gold":347,"diamond":20,"items":[{"itemId":"chest_bronze","quantity":1,"dropRate":1}]}', '{"chapterName":"🌲 暗夜森林","stageName":"暗影領域","description":"連光都無法穿透的黑暗核心地帶","bgTheme":"forest","difficulty":16,"recommendedLevel":20,"isBoss":true,"chapterIcon":"🌲"}');

-- ═══════════════════════════════════════════════════════════
-- 第 3 章 🏜️ 死寂荒原
-- ═══════════════════════════════════════════════════════════

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('3-1', 3, 1, '[{"heroId":4,"slot":1,"levelMultiplier":1,"hpMultiplier":1.2,"atkMultiplier":0.8,"defMultiplier":0.8,"speedMultiplier":1.14},{"heroId":5,"slot":2,"levelMultiplier":1,"hpMultiplier":1.2,"atkMultiplier":0.8,"defMultiplier":0.8,"speedMultiplier":1.14},{"heroId":6,"slot":3,"levelMultiplier":1,"hpMultiplier":1.2,"atkMultiplier":0.8,"defMultiplier":0.8,"speedMultiplier":1.14}]', '{"exp":237,"gold":364,"diamond":0}', '{"chapterName":"🏜️ 死寂荒原","stageName":"荒漠公路","description":"龜裂的柏油路延伸至地平線盡頭","bgTheme":"wasteland","difficulty":17,"recommendedLevel":21,"isBoss":false,"chapterIcon":"🏜️"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('3-2', 3, 2, '[{"heroId":4,"slot":1,"levelMultiplier":1,"hpMultiplier":1.29,"atkMultiplier":0.86,"defMultiplier":0.83,"speedMultiplier":1.14},{"heroId":5,"slot":2,"levelMultiplier":1,"hpMultiplier":1.29,"atkMultiplier":0.86,"defMultiplier":0.83,"speedMultiplier":1.14},{"heroId":6,"slot":3,"levelMultiplier":1,"hpMultiplier":1.29,"atkMultiplier":0.86,"defMultiplier":0.83,"speedMultiplier":1.14}]', '{"exp":249,"gold":382,"diamond":0}', '{"chapterName":"🏜️ 死寂荒原","stageName":"廢棄礦坑","description":"坑道深處傳來金屬敲擊的回聲","bgTheme":"wasteland","difficulty":18,"recommendedLevel":22,"isBoss":false,"chapterIcon":"🏜️"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('3-3', 3, 3, '[{"heroId":4,"slot":1,"levelMultiplier":1,"hpMultiplier":1.37,"atkMultiplier":0.91,"defMultiplier":0.86,"speedMultiplier":1.14},{"heroId":5,"slot":2,"levelMultiplier":1,"hpMultiplier":1.37,"atkMultiplier":0.91,"defMultiplier":0.86,"speedMultiplier":1.14},{"heroId":6,"slot":3,"levelMultiplier":1,"hpMultiplier":1.37,"atkMultiplier":0.91,"defMultiplier":0.86,"speedMultiplier":1.14}]', '{"exp":261,"gold":400,"diamond":0}', '{"chapterName":"🏜️ 死寂荒原","stageName":"輻射區域","description":"蓋格計數器瘋狂跳動的禁區","bgTheme":"wasteland","difficulty":19,"recommendedLevel":23,"isBoss":false,"chapterIcon":"🏜️"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('3-4', 3, 4, '[{"heroId":4,"slot":1,"levelMultiplier":1,"hpMultiplier":1.46,"atkMultiplier":0.97,"defMultiplier":0.89,"speedMultiplier":1.14},{"heroId":5,"slot":2,"levelMultiplier":1,"hpMultiplier":1.46,"atkMultiplier":0.97,"defMultiplier":0.89,"speedMultiplier":1.14},{"heroId":6,"slot":3,"levelMultiplier":1,"hpMultiplier":1.46,"atkMultiplier":0.97,"defMultiplier":0.89,"speedMultiplier":1.14}]', '{"exp":273,"gold":418,"diamond":0}', '{"chapterName":"🏜️ 死寂荒原","stageName":"骨塚墓地","description":"堆疊如山的遺骸間飄蕩著磷火","bgTheme":"wasteland","difficulty":20,"recommendedLevel":24,"isBoss":false,"chapterIcon":"🏜️"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('3-5', 3, 5, '[{"heroId":4,"slot":1,"levelMultiplier":1,"hpMultiplier":1.54,"atkMultiplier":1.03,"defMultiplier":0.91,"speedMultiplier":1.14},{"heroId":5,"slot":2,"levelMultiplier":1,"hpMultiplier":1.54,"atkMultiplier":1.03,"defMultiplier":0.91,"speedMultiplier":1.14},{"heroId":6,"slot":3,"levelMultiplier":1,"hpMultiplier":1.54,"atkMultiplier":1.03,"defMultiplier":0.91,"speedMultiplier":1.14},{"heroId":7,"slot":4,"levelMultiplier":1,"hpMultiplier":1.54,"atkMultiplier":1.03,"defMultiplier":0.91,"speedMultiplier":1.14}]', '{"exp":285,"gold":436,"diamond":0}', '{"chapterName":"🏜️ 死寂荒原","stageName":"軍事基地","description":"荒廢的碉堡裡散落著彈殼與殘骸","bgTheme":"wasteland","difficulty":21,"recommendedLevel":26,"isBoss":false,"chapterIcon":"🏜️"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('3-6', 3, 6, '[{"heroId":4,"slot":1,"levelMultiplier":1,"hpMultiplier":1.63,"atkMultiplier":1.09,"defMultiplier":0.94,"speedMultiplier":1.14},{"heroId":5,"slot":2,"levelMultiplier":1,"hpMultiplier":1.63,"atkMultiplier":1.09,"defMultiplier":0.94,"speedMultiplier":1.14},{"heroId":6,"slot":3,"levelMultiplier":1,"hpMultiplier":1.63,"atkMultiplier":1.09,"defMultiplier":0.94,"speedMultiplier":1.14},{"heroId":7,"slot":4,"levelMultiplier":1,"hpMultiplier":1.63,"atkMultiplier":1.09,"defMultiplier":0.94,"speedMultiplier":1.14}]', '{"exp":297,"gold":453,"diamond":0}', '{"chapterName":"🏜️ 死寂荒原","stageName":"生化實驗室","description":"破碎的試管流出螢光色液體","bgTheme":"wasteland","difficulty":22,"recommendedLevel":27,"isBoss":false,"chapterIcon":"🏜️"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('3-7', 3, 7, '[{"heroId":4,"slot":1,"levelMultiplier":1,"hpMultiplier":1.71,"atkMultiplier":1.14,"defMultiplier":0.97,"speedMultiplier":1.14},{"heroId":5,"slot":2,"levelMultiplier":1,"hpMultiplier":1.71,"atkMultiplier":1.14,"defMultiplier":0.97,"speedMultiplier":1.14},{"heroId":6,"slot":3,"levelMultiplier":1,"hpMultiplier":1.71,"atkMultiplier":1.14,"defMultiplier":0.97,"speedMultiplier":1.14},{"heroId":7,"slot":4,"levelMultiplier":1,"hpMultiplier":1.71,"atkMultiplier":1.14,"defMultiplier":0.97,"speedMultiplier":1.14}]', '{"exp":309,"gold":471,"diamond":0}', '{"chapterName":"🏜️ 死寂荒原","stageName":"核電廠遺址","description":"冷卻塔的裂縫中滲出不祥光芒","bgTheme":"wasteland","difficulty":23,"recommendedLevel":28,"isBoss":false,"chapterIcon":"🏜️"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('3-8', 3, 8, '[{"heroId":4,"slot":1,"levelMultiplier":1,"hpMultiplier":1.8,"atkMultiplier":1.2,"defMultiplier":1,"speedMultiplier":1.14},{"heroId":5,"slot":2,"levelMultiplier":1,"hpMultiplier":1.8,"atkMultiplier":1.2,"defMultiplier":1,"speedMultiplier":1.14},{"heroId":6,"slot":3,"levelMultiplier":1,"hpMultiplier":1.8,"atkMultiplier":1.2,"defMultiplier":1,"speedMultiplier":1.14},{"heroId":7,"slot":4,"levelMultiplier":1,"hpMultiplier":2.7,"atkMultiplier":1.8,"defMultiplier":1.5,"speedMultiplier":1.03}]', '{"exp":321,"gold":489,"diamond":20,"items":[{"itemId":"chest_bronze","quantity":1,"dropRate":1}]}', '{"chapterName":"🏜️ 死寂荒原","stageName":"末日祭壇","description":"以骨骸築成的祭壇散發死亡氣息","bgTheme":"wasteland","difficulty":24,"recommendedLevel":30,"isBoss":true,"chapterIcon":"🏜️"}');

-- ═══════════════════════════════════════════════════════════
-- 第 4 章 🏭 工業廢墟
-- ═══════════════════════════════════════════════════════════

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('4-1', 4, 1, '[{"heroId":5,"slot":1,"levelMultiplier":1,"hpMultiplier":1.8,"atkMultiplier":1.2,"defMultiplier":1,"speedMultiplier":1.21},{"heroId":6,"slot":2,"levelMultiplier":1,"hpMultiplier":1.8,"atkMultiplier":1.2,"defMultiplier":1,"speedMultiplier":1.21},{"heroId":7,"slot":3,"levelMultiplier":1,"hpMultiplier":1.8,"atkMultiplier":1.2,"defMultiplier":1,"speedMultiplier":1.21}]', '{"exp":333,"gold":507,"diamond":0}', '{"chapterName":"🏭 工業廢墟","stageName":"廢棄工廠入口","description":"生鏽的鐵門後傳來機械運轉聲","bgTheme":"factory","difficulty":25,"recommendedLevel":31,"isBoss":false,"chapterIcon":"🏭"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('4-2', 4, 2, '[{"heroId":5,"slot":1,"levelMultiplier":1,"hpMultiplier":1.9,"atkMultiplier":1.26,"defMultiplier":1.04,"speedMultiplier":1.21},{"heroId":6,"slot":2,"levelMultiplier":1,"hpMultiplier":1.9,"atkMultiplier":1.26,"defMultiplier":1.04,"speedMultiplier":1.21},{"heroId":7,"slot":3,"levelMultiplier":1,"hpMultiplier":1.9,"atkMultiplier":1.26,"defMultiplier":1.04,"speedMultiplier":1.21}]', '{"exp":345,"gold":524,"diamond":0}', '{"chapterName":"🏭 工業廢墟","stageName":"鍋爐房","description":"高溫蒸氣從破裂的管道中噴出","bgTheme":"factory","difficulty":26,"recommendedLevel":32,"isBoss":false,"chapterIcon":"🏭"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('4-3', 4, 3, '[{"heroId":5,"slot":1,"levelMultiplier":1,"hpMultiplier":2,"atkMultiplier":1.31,"defMultiplier":1.09,"speedMultiplier":1.21},{"heroId":6,"slot":2,"levelMultiplier":1,"hpMultiplier":2,"atkMultiplier":1.31,"defMultiplier":1.09,"speedMultiplier":1.21},{"heroId":7,"slot":3,"levelMultiplier":1,"hpMultiplier":2,"atkMultiplier":1.31,"defMultiplier":1.09,"speedMultiplier":1.21},{"heroId":8,"slot":4,"levelMultiplier":1,"hpMultiplier":2,"atkMultiplier":1.31,"defMultiplier":1.09,"speedMultiplier":1.21}]', '{"exp":357,"gold":542,"diamond":0}', '{"chapterName":"🏭 工業廢墟","stageName":"裝配車間","description":"停滯的流水線上擺滿半成品武器","bgTheme":"factory","difficulty":27,"recommendedLevel":33,"isBoss":false,"chapterIcon":"🏭"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('4-4', 4, 4, '[{"heroId":5,"slot":1,"levelMultiplier":1,"hpMultiplier":2.1,"atkMultiplier":1.37,"defMultiplier":1.13,"speedMultiplier":1.21},{"heroId":6,"slot":2,"levelMultiplier":1,"hpMultiplier":2.1,"atkMultiplier":1.37,"defMultiplier":1.13,"speedMultiplier":1.21},{"heroId":7,"slot":3,"levelMultiplier":1,"hpMultiplier":2.1,"atkMultiplier":1.37,"defMultiplier":1.13,"speedMultiplier":1.21},{"heroId":8,"slot":4,"levelMultiplier":1,"hpMultiplier":2.1,"atkMultiplier":1.37,"defMultiplier":1.13,"speedMultiplier":1.21}]', '{"exp":369,"gold":560,"diamond":0}', '{"chapterName":"🏭 工業廢墟","stageName":"化學儲槽區","description":"洩漏的化學藥劑侵蝕著地面","bgTheme":"factory","difficulty":28,"recommendedLevel":34,"isBoss":false,"chapterIcon":"🏭"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('4-5', 4, 5, '[{"heroId":5,"slot":1,"levelMultiplier":1,"hpMultiplier":2.2,"atkMultiplier":1.43,"defMultiplier":1.17,"speedMultiplier":1.21},{"heroId":6,"slot":2,"levelMultiplier":1,"hpMultiplier":2.2,"atkMultiplier":1.43,"defMultiplier":1.17,"speedMultiplier":1.21},{"heroId":7,"slot":3,"levelMultiplier":1,"hpMultiplier":2.2,"atkMultiplier":1.43,"defMultiplier":1.17,"speedMultiplier":1.21},{"heroId":8,"slot":4,"levelMultiplier":1,"hpMultiplier":2.2,"atkMultiplier":1.43,"defMultiplier":1.17,"speedMultiplier":1.21}]', '{"exp":381,"gold":578,"diamond":0}', '{"chapterName":"🏭 工業廢墟","stageName":"地下管道","description":"狹窄的管道中迴盪著爬行聲","bgTheme":"factory","difficulty":29,"recommendedLevel":36,"isBoss":false,"chapterIcon":"🏭"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('4-6', 4, 6, '[{"heroId":5,"slot":1,"levelMultiplier":1,"hpMultiplier":2.3,"atkMultiplier":1.49,"defMultiplier":1.21,"speedMultiplier":1.21},{"heroId":6,"slot":2,"levelMultiplier":1,"hpMultiplier":2.3,"atkMultiplier":1.49,"defMultiplier":1.21,"speedMultiplier":1.21},{"heroId":7,"slot":3,"levelMultiplier":1,"hpMultiplier":2.3,"atkMultiplier":1.49,"defMultiplier":1.21,"speedMultiplier":1.21},{"heroId":8,"slot":4,"levelMultiplier":1,"hpMultiplier":2.3,"atkMultiplier":1.49,"defMultiplier":1.21,"speedMultiplier":1.21}]', '{"exp":393,"gold":596,"diamond":0}', '{"chapterName":"🏭 工業廢墟","stageName":"高壓電站","description":"電弧在廢棄設備間不斷跳躍","bgTheme":"factory","difficulty":30,"recommendedLevel":37,"isBoss":false,"chapterIcon":"🏭"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('4-7', 4, 7, '[{"heroId":5,"slot":1,"levelMultiplier":1,"hpMultiplier":2.4,"atkMultiplier":1.54,"defMultiplier":1.26,"speedMultiplier":1.21},{"heroId":6,"slot":2,"levelMultiplier":1,"hpMultiplier":2.4,"atkMultiplier":1.54,"defMultiplier":1.26,"speedMultiplier":1.21},{"heroId":7,"slot":3,"levelMultiplier":1,"hpMultiplier":2.4,"atkMultiplier":1.54,"defMultiplier":1.26,"speedMultiplier":1.21},{"heroId":8,"slot":4,"levelMultiplier":1,"hpMultiplier":2.4,"atkMultiplier":1.54,"defMultiplier":1.26,"speedMultiplier":1.21}]', '{"exp":405,"gold":613,"diamond":0}', '{"chapterName":"🏭 工業廢墟","stageName":"煙囪頂層","description":"工廠最高處俯瞰末日的全景","bgTheme":"factory","difficulty":31,"recommendedLevel":38,"isBoss":false,"chapterIcon":"🏭"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('4-8', 4, 8, '[{"heroId":5,"slot":1,"levelMultiplier":1,"hpMultiplier":2.5,"atkMultiplier":1.6,"defMultiplier":1.3,"speedMultiplier":1.21},{"heroId":6,"slot":2,"levelMultiplier":1,"hpMultiplier":2.5,"atkMultiplier":1.6,"defMultiplier":1.3,"speedMultiplier":1.21},{"heroId":7,"slot":3,"levelMultiplier":1,"hpMultiplier":2.5,"atkMultiplier":1.6,"defMultiplier":1.3,"speedMultiplier":1.21},{"heroId":8,"slot":4,"levelMultiplier":1,"hpMultiplier":2.5,"atkMultiplier":1.6,"defMultiplier":1.3,"speedMultiplier":1.21},{"heroId":9,"slot":5,"levelMultiplier":1,"hpMultiplier":3.75,"atkMultiplier":2.4,"defMultiplier":1.95,"speedMultiplier":1.09}]', '{"exp":417,"gold":631,"diamond":30,"items":[{"itemId":"chest_silver","quantity":1,"dropRate":1}]}', '{"chapterName":"🏭 工業廢墟","stageName":"機械巨獸","description":"由廢鐵拼裝的巨型機械怪物甦醒","bgTheme":"factory","difficulty":32,"recommendedLevel":40,"isBoss":true,"chapterIcon":"🏭"}');

-- ═══════════════════════════════════════════════════════════
-- 第 5 章 🏥 沉默醫院
-- ═══════════════════════════════════════════════════════════

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('5-1', 5, 1, '[{"heroId":7,"slot":1,"levelMultiplier":1,"hpMultiplier":2.5,"atkMultiplier":1.6,"defMultiplier":1.3,"speedMultiplier":1.29},{"heroId":8,"slot":2,"levelMultiplier":1,"hpMultiplier":2.5,"atkMultiplier":1.6,"defMultiplier":1.3,"speedMultiplier":1.29},{"heroId":9,"slot":3,"levelMultiplier":1,"hpMultiplier":2.5,"atkMultiplier":1.6,"defMultiplier":1.3,"speedMultiplier":1.29},{"heroId":10,"slot":4,"levelMultiplier":1,"hpMultiplier":2.5,"atkMultiplier":1.6,"defMultiplier":1.3,"speedMultiplier":1.29}]', '{"exp":428,"gold":649,"diamond":0}', '{"chapterName":"🏥 沉默醫院","stageName":"急診大廳","description":"候診椅上的骷髏仍保持等待姿勢","bgTheme":"hospital","difficulty":33,"recommendedLevel":41,"isBoss":false,"chapterIcon":"🏥"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('5-2', 5, 2, '[{"heroId":7,"slot":1,"levelMultiplier":1,"hpMultiplier":2.64,"atkMultiplier":1.66,"defMultiplier":1.34,"speedMultiplier":1.29},{"heroId":8,"slot":2,"levelMultiplier":1,"hpMultiplier":2.64,"atkMultiplier":1.66,"defMultiplier":1.34,"speedMultiplier":1.29},{"heroId":9,"slot":3,"levelMultiplier":1,"hpMultiplier":2.64,"atkMultiplier":1.66,"defMultiplier":1.34,"speedMultiplier":1.29},{"heroId":10,"slot":4,"levelMultiplier":1,"hpMultiplier":2.64,"atkMultiplier":1.66,"defMultiplier":1.34,"speedMultiplier":1.29}]', '{"exp":440,"gold":667,"diamond":0}', '{"chapterName":"🏥 沉默醫院","stageName":"手術室","description":"無影燈下的手術台沾滿乾涸血跡","bgTheme":"hospital","difficulty":34,"recommendedLevel":42,"isBoss":false,"chapterIcon":"🏥"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('5-3', 5, 3, '[{"heroId":7,"slot":1,"levelMultiplier":1,"hpMultiplier":2.79,"atkMultiplier":1.71,"defMultiplier":1.39,"speedMultiplier":1.29},{"heroId":8,"slot":2,"levelMultiplier":1,"hpMultiplier":2.79,"atkMultiplier":1.71,"defMultiplier":1.39,"speedMultiplier":1.29},{"heroId":9,"slot":3,"levelMultiplier":1,"hpMultiplier":2.79,"atkMultiplier":1.71,"defMultiplier":1.39,"speedMultiplier":1.29},{"heroId":10,"slot":4,"levelMultiplier":1,"hpMultiplier":2.79,"atkMultiplier":1.71,"defMultiplier":1.39,"speedMultiplier":1.29}]', '{"exp":452,"gold":684,"diamond":0}', '{"chapterName":"🏥 沉默醫院","stageName":"太平間","description":"冷藏櫃的門被從內側撞開了","bgTheme":"hospital","difficulty":35,"recommendedLevel":43,"isBoss":false,"chapterIcon":"🏥"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('5-4', 5, 4, '[{"heroId":7,"slot":1,"levelMultiplier":1,"hpMultiplier":2.93,"atkMultiplier":1.77,"defMultiplier":1.43,"speedMultiplier":1.29},{"heroId":8,"slot":2,"levelMultiplier":1,"hpMultiplier":2.93,"atkMultiplier":1.77,"defMultiplier":1.43,"speedMultiplier":1.29},{"heroId":9,"slot":3,"levelMultiplier":1,"hpMultiplier":2.93,"atkMultiplier":1.77,"defMultiplier":1.43,"speedMultiplier":1.29},{"heroId":10,"slot":4,"levelMultiplier":1,"hpMultiplier":2.93,"atkMultiplier":1.77,"defMultiplier":1.43,"speedMultiplier":1.29}]', '{"exp":464,"gold":702,"diamond":0}', '{"chapterName":"🏥 沉默醫院","stageName":"精神病房","description":"牆上的抓痕和塗鴉述說著瘋狂","bgTheme":"hospital","difficulty":36,"recommendedLevel":44,"isBoss":false,"chapterIcon":"🏥"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('5-5', 5, 5, '[{"heroId":7,"slot":1,"levelMultiplier":1,"hpMultiplier":3.07,"atkMultiplier":1.83,"defMultiplier":1.47,"speedMultiplier":1.29},{"heroId":8,"slot":2,"levelMultiplier":1,"hpMultiplier":3.07,"atkMultiplier":1.83,"defMultiplier":1.47,"speedMultiplier":1.29},{"heroId":9,"slot":3,"levelMultiplier":1,"hpMultiplier":3.07,"atkMultiplier":1.83,"defMultiplier":1.47,"speedMultiplier":1.29},{"heroId":10,"slot":4,"levelMultiplier":1,"hpMultiplier":3.07,"atkMultiplier":1.83,"defMultiplier":1.47,"speedMultiplier":1.29}]', '{"exp":476,"gold":720,"diamond":0}', '{"chapterName":"🏥 沉默醫院","stageName":"藥品倉庫","description":"散落的藥瓶間藏著變異的線索","bgTheme":"hospital","difficulty":37,"recommendedLevel":46,"isBoss":false,"chapterIcon":"🏥"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('5-6', 5, 6, '[{"heroId":7,"slot":1,"levelMultiplier":1,"hpMultiplier":3.21,"atkMultiplier":1.89,"defMultiplier":1.51,"speedMultiplier":1.29},{"heroId":8,"slot":2,"levelMultiplier":1,"hpMultiplier":3.21,"atkMultiplier":1.89,"defMultiplier":1.51,"speedMultiplier":1.29},{"heroId":9,"slot":3,"levelMultiplier":1,"hpMultiplier":3.21,"atkMultiplier":1.89,"defMultiplier":1.51,"speedMultiplier":1.29},{"heroId":10,"slot":4,"levelMultiplier":1,"hpMultiplier":3.21,"atkMultiplier":1.89,"defMultiplier":1.51,"speedMultiplier":1.29},{"heroId":11,"slot":5,"levelMultiplier":1,"hpMultiplier":3.21,"atkMultiplier":1.89,"defMultiplier":1.51,"speedMultiplier":1.29}]', '{"exp":488,"gold":738,"diamond":0}', '{"chapterName":"🏥 沉默醫院","stageName":"頂樓花園","description":"枯萎的花園中唯有食肉植物茂盛","bgTheme":"hospital","difficulty":38,"recommendedLevel":47,"isBoss":false,"chapterIcon":"🏥"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('5-7', 5, 7, '[{"heroId":7,"slot":1,"levelMultiplier":1,"hpMultiplier":3.36,"atkMultiplier":1.94,"defMultiplier":1.56,"speedMultiplier":1.29},{"heroId":8,"slot":2,"levelMultiplier":1,"hpMultiplier":3.36,"atkMultiplier":1.94,"defMultiplier":1.56,"speedMultiplier":1.29},{"heroId":9,"slot":3,"levelMultiplier":1,"hpMultiplier":3.36,"atkMultiplier":1.94,"defMultiplier":1.56,"speedMultiplier":1.29},{"heroId":10,"slot":4,"levelMultiplier":1,"hpMultiplier":3.36,"atkMultiplier":1.94,"defMultiplier":1.56,"speedMultiplier":1.29},{"heroId":11,"slot":5,"levelMultiplier":1,"hpMultiplier":3.36,"atkMultiplier":1.94,"defMultiplier":1.56,"speedMultiplier":1.29}]', '{"exp":500,"gold":756,"diamond":0}', '{"chapterName":"🏥 沉默醫院","stageName":"院長辦公室","description":"密封的檔案記錄了感染的真相","bgTheme":"hospital","difficulty":39,"recommendedLevel":48,"isBoss":false,"chapterIcon":"🏥"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('5-8', 5, 8, '[{"heroId":7,"slot":1,"levelMultiplier":1,"hpMultiplier":3.5,"atkMultiplier":2,"defMultiplier":1.6,"speedMultiplier":1.29},{"heroId":8,"slot":2,"levelMultiplier":1,"hpMultiplier":3.5,"atkMultiplier":2,"defMultiplier":1.6,"speedMultiplier":1.29},{"heroId":9,"slot":3,"levelMultiplier":1,"hpMultiplier":3.5,"atkMultiplier":2,"defMultiplier":1.6,"speedMultiplier":1.29},{"heroId":10,"slot":4,"levelMultiplier":1,"hpMultiplier":3.5,"atkMultiplier":2,"defMultiplier":1.6,"speedMultiplier":1.29},{"heroId":11,"slot":5,"levelMultiplier":1,"hpMultiplier":5.25,"atkMultiplier":3,"defMultiplier":2.4,"speedMultiplier":1.16}]', '{"exp":512,"gold":773,"diamond":30,"items":[{"itemId":"chest_silver","quantity":1,"dropRate":1}]}', '{"chapterName":"🏥 沉默醫院","stageName":"零號病患","description":"一切的起源就沉睡在這張病床上","bgTheme":"hospital","difficulty":40,"recommendedLevel":50,"isBoss":true,"chapterIcon":"🏥"}');

-- ═══════════════════════════════════════════════════════════
-- 第 6 章 🏚️ 廢棄住宅區
-- ═══════════════════════════════════════════════════════════

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('6-1', 6, 1, '[{"heroId":8,"slot":1,"levelMultiplier":1,"hpMultiplier":3.5,"atkMultiplier":2,"defMultiplier":1.6,"speedMultiplier":1.36},{"heroId":9,"slot":2,"levelMultiplier":1,"hpMultiplier":3.5,"atkMultiplier":2,"defMultiplier":1.6,"speedMultiplier":1.36},{"heroId":10,"slot":3,"levelMultiplier":1,"hpMultiplier":3.5,"atkMultiplier":2,"defMultiplier":1.6,"speedMultiplier":1.36},{"heroId":11,"slot":4,"levelMultiplier":1,"hpMultiplier":3.5,"atkMultiplier":2,"defMultiplier":1.6,"speedMultiplier":1.36}]', '{"exp":524,"gold":791,"diamond":0}', '{"chapterName":"🏚️ 廢棄住宅區","stageName":"社區入口","description":"倒塌的門禁旁堆滿雜物路障","bgTheme":"residential","difficulty":41,"recommendedLevel":51,"isBoss":false,"chapterIcon":"🏚️"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('6-2', 6, 2, '[{"heroId":8,"slot":1,"levelMultiplier":1,"hpMultiplier":3.64,"atkMultiplier":2.07,"defMultiplier":1.66,"speedMultiplier":1.36},{"heroId":9,"slot":2,"levelMultiplier":1,"hpMultiplier":3.64,"atkMultiplier":2.07,"defMultiplier":1.66,"speedMultiplier":1.36},{"heroId":10,"slot":3,"levelMultiplier":1,"hpMultiplier":3.64,"atkMultiplier":2.07,"defMultiplier":1.66,"speedMultiplier":1.36},{"heroId":11,"slot":4,"levelMultiplier":1,"hpMultiplier":3.64,"atkMultiplier":2.07,"defMultiplier":1.66,"speedMultiplier":1.36}]', '{"exp":536,"gold":809,"diamond":0}', '{"chapterName":"🏚️ 廢棄住宅區","stageName":"便利商店","description":"貨架散落一地只剩過期的罐頭","bgTheme":"residential","difficulty":42,"recommendedLevel":52,"isBoss":false,"chapterIcon":"🏚️"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('6-3', 6, 3, '[{"heroId":8,"slot":1,"levelMultiplier":1,"hpMultiplier":3.79,"atkMultiplier":2.14,"defMultiplier":1.71,"speedMultiplier":1.36},{"heroId":9,"slot":2,"levelMultiplier":1,"hpMultiplier":3.79,"atkMultiplier":2.14,"defMultiplier":1.71,"speedMultiplier":1.36},{"heroId":10,"slot":3,"levelMultiplier":1,"hpMultiplier":3.79,"atkMultiplier":2.14,"defMultiplier":1.71,"speedMultiplier":1.36},{"heroId":11,"slot":4,"levelMultiplier":1,"hpMultiplier":3.79,"atkMultiplier":2.14,"defMultiplier":1.71,"speedMultiplier":1.36},{"heroId":12,"slot":5,"levelMultiplier":1,"hpMultiplier":3.79,"atkMultiplier":2.14,"defMultiplier":1.71,"speedMultiplier":1.36}]', '{"exp":548,"gold":827,"diamond":0}', '{"chapterName":"🏚️ 廢棄住宅區","stageName":"遊樂場","description":"生鏽的鞦韆在無風中自己搖擺","bgTheme":"residential","difficulty":43,"recommendedLevel":53,"isBoss":false,"chapterIcon":"🏚️"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('6-4', 6, 4, '[{"heroId":8,"slot":1,"levelMultiplier":1,"hpMultiplier":3.93,"atkMultiplier":2.21,"defMultiplier":1.77,"speedMultiplier":1.36},{"heroId":9,"slot":2,"levelMultiplier":1,"hpMultiplier":3.93,"atkMultiplier":2.21,"defMultiplier":1.77,"speedMultiplier":1.36},{"heroId":10,"slot":3,"levelMultiplier":1,"hpMultiplier":3.93,"atkMultiplier":2.21,"defMultiplier":1.77,"speedMultiplier":1.36},{"heroId":11,"slot":4,"levelMultiplier":1,"hpMultiplier":3.93,"atkMultiplier":2.21,"defMultiplier":1.77,"speedMultiplier":1.36},{"heroId":12,"slot":5,"levelMultiplier":1,"hpMultiplier":3.93,"atkMultiplier":2.21,"defMultiplier":1.77,"speedMultiplier":1.36}]', '{"exp":560,"gold":844,"diamond":0}', '{"chapterName":"🏚️ 廢棄住宅區","stageName":"高層公寓","description":"窗口垂下的布條寫著求救訊息","bgTheme":"residential","difficulty":44,"recommendedLevel":54,"isBoss":false,"chapterIcon":"🏚️"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('6-5', 6, 5, '[{"heroId":8,"slot":1,"levelMultiplier":1,"hpMultiplier":4.07,"atkMultiplier":2.29,"defMultiplier":1.83,"speedMultiplier":1.36},{"heroId":9,"slot":2,"levelMultiplier":1,"hpMultiplier":4.07,"atkMultiplier":2.29,"defMultiplier":1.83,"speedMultiplier":1.36},{"heroId":10,"slot":3,"levelMultiplier":1,"hpMultiplier":4.07,"atkMultiplier":2.29,"defMultiplier":1.83,"speedMultiplier":1.36},{"heroId":11,"slot":4,"levelMultiplier":1,"hpMultiplier":4.07,"atkMultiplier":2.29,"defMultiplier":1.83,"speedMultiplier":1.36},{"heroId":12,"slot":5,"levelMultiplier":1,"hpMultiplier":4.07,"atkMultiplier":2.29,"defMultiplier":1.83,"speedMultiplier":1.36}]', '{"exp":572,"gold":862,"diamond":0}', '{"chapterName":"🏚️ 廢棄住宅區","stageName":"頂樓天台","description":"天台上的營火灰燼還留有餘溫","bgTheme":"residential","difficulty":45,"recommendedLevel":56,"isBoss":false,"chapterIcon":"🏚️"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('6-6', 6, 6, '[{"heroId":8,"slot":1,"levelMultiplier":1,"hpMultiplier":4.21,"atkMultiplier":2.36,"defMultiplier":1.89,"speedMultiplier":1.36},{"heroId":9,"slot":2,"levelMultiplier":1,"hpMultiplier":4.21,"atkMultiplier":2.36,"defMultiplier":1.89,"speedMultiplier":1.36},{"heroId":10,"slot":3,"levelMultiplier":1,"hpMultiplier":4.21,"atkMultiplier":2.36,"defMultiplier":1.89,"speedMultiplier":1.36},{"heroId":11,"slot":4,"levelMultiplier":1,"hpMultiplier":4.21,"atkMultiplier":2.36,"defMultiplier":1.89,"speedMultiplier":1.36},{"heroId":12,"slot":5,"levelMultiplier":1,"hpMultiplier":4.21,"atkMultiplier":2.36,"defMultiplier":1.89,"speedMultiplier":1.36}]', '{"exp":584,"gold":880,"diamond":0}', '{"chapterName":"🏚️ 廢棄住宅區","stageName":"地下室","description":"黑暗的地下室傳來沉重的呼吸聲","bgTheme":"residential","difficulty":46,"recommendedLevel":57,"isBoss":false,"chapterIcon":"🏚️"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('6-7', 6, 7, '[{"heroId":8,"slot":1,"levelMultiplier":1,"hpMultiplier":4.36,"atkMultiplier":2.43,"defMultiplier":1.94,"speedMultiplier":1.36},{"heroId":9,"slot":2,"levelMultiplier":1,"hpMultiplier":4.36,"atkMultiplier":2.43,"defMultiplier":1.94,"speedMultiplier":1.36},{"heroId":10,"slot":3,"levelMultiplier":1,"hpMultiplier":4.36,"atkMultiplier":2.43,"defMultiplier":1.94,"speedMultiplier":1.36},{"heroId":11,"slot":4,"levelMultiplier":1,"hpMultiplier":4.36,"atkMultiplier":2.43,"defMultiplier":1.94,"speedMultiplier":1.36},{"heroId":12,"slot":5,"levelMultiplier":1,"hpMultiplier":4.36,"atkMultiplier":2.43,"defMultiplier":1.94,"speedMultiplier":1.36}]', '{"exp":596,"gold":898,"diamond":0}', '{"chapterName":"🏚️ 廢棄住宅區","stageName":"防空洞","description":"冷戰時期的避難所成了屍群巢穴","bgTheme":"residential","difficulty":47,"recommendedLevel":58,"isBoss":false,"chapterIcon":"🏚️"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('6-8', 6, 8, '[{"heroId":8,"slot":1,"levelMultiplier":1,"hpMultiplier":4.5,"atkMultiplier":2.5,"defMultiplier":2,"speedMultiplier":1.36},{"heroId":9,"slot":2,"levelMultiplier":1,"hpMultiplier":4.5,"atkMultiplier":2.5,"defMultiplier":2,"speedMultiplier":1.36},{"heroId":10,"slot":3,"levelMultiplier":1,"hpMultiplier":4.5,"atkMultiplier":2.5,"defMultiplier":2,"speedMultiplier":1.36},{"heroId":11,"slot":4,"levelMultiplier":1,"hpMultiplier":4.5,"atkMultiplier":2.5,"defMultiplier":2,"speedMultiplier":1.36},{"heroId":12,"slot":5,"levelMultiplier":1,"hpMultiplier":6.75,"atkMultiplier":3.75,"defMultiplier":3,"speedMultiplier":1.22}]', '{"exp":608,"gold":916,"diamond":50,"items":[{"itemId":"chest_gold","quantity":1,"dropRate":1}]}', '{"chapterName":"🏚️ 廢棄住宅區","stageName":"社區守衛者","description":"曾經的保全隊長已成為不死首領","bgTheme":"residential","difficulty":48,"recommendedLevel":60,"isBoss":true,"chapterIcon":"🏚️"}');

-- ═══════════════════════════════════════════════════════════
-- 第 7 章 🚇 地下交通網
-- ═══════════════════════════════════════════════════════════

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('7-1', 7, 1, '[{"heroId":10,"slot":1,"levelMultiplier":1,"hpMultiplier":4.5,"atkMultiplier":2.5,"defMultiplier":2,"speedMultiplier":1.43},{"heroId":11,"slot":2,"levelMultiplier":1,"hpMultiplier":4.5,"atkMultiplier":2.5,"defMultiplier":2,"speedMultiplier":1.43},{"heroId":12,"slot":3,"levelMultiplier":1,"hpMultiplier":4.5,"atkMultiplier":2.5,"defMultiplier":2,"speedMultiplier":1.43},{"heroId":13,"slot":4,"levelMultiplier":1,"hpMultiplier":4.5,"atkMultiplier":2.5,"defMultiplier":2,"speedMultiplier":1.43},{"heroId":10,"slot":5,"levelMultiplier":1,"hpMultiplier":4.5,"atkMultiplier":2.5,"defMultiplier":2,"speedMultiplier":1.43}]', '{"exp":620,"gold":933,"diamond":0}', '{"chapterName":"🚇 地下交通網","stageName":"地鐵站入口","description":"電扶梯盡頭是無盡的黑暗深淵","bgTheme":"underground","difficulty":49,"recommendedLevel":61,"isBoss":false,"chapterIcon":"🚇"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('7-2', 7, 2, '[{"heroId":10,"slot":1,"levelMultiplier":1,"hpMultiplier":4.64,"atkMultiplier":2.57,"defMultiplier":2.07,"speedMultiplier":1.43},{"heroId":11,"slot":2,"levelMultiplier":1,"hpMultiplier":4.64,"atkMultiplier":2.57,"defMultiplier":2.07,"speedMultiplier":1.43},{"heroId":12,"slot":3,"levelMultiplier":1,"hpMultiplier":4.64,"atkMultiplier":2.57,"defMultiplier":2.07,"speedMultiplier":1.43},{"heroId":13,"slot":4,"levelMultiplier":1,"hpMultiplier":4.64,"atkMultiplier":2.57,"defMultiplier":2.07,"speedMultiplier":1.43},{"heroId":10,"slot":5,"levelMultiplier":1,"hpMultiplier":4.64,"atkMultiplier":2.57,"defMultiplier":2.07,"speedMultiplier":1.43}]', '{"exp":632,"gold":951,"diamond":0}', '{"chapterName":"🚇 地下交通網","stageName":"月台廢墟","description":"停靠的列車車窗後有東西在動","bgTheme":"underground","difficulty":50,"recommendedLevel":62,"isBoss":false,"chapterIcon":"🚇"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('7-3', 7, 3, '[{"heroId":10,"slot":1,"levelMultiplier":1,"hpMultiplier":4.79,"atkMultiplier":2.64,"defMultiplier":2.14,"speedMultiplier":1.43},{"heroId":11,"slot":2,"levelMultiplier":1,"hpMultiplier":4.79,"atkMultiplier":2.64,"defMultiplier":2.14,"speedMultiplier":1.43},{"heroId":12,"slot":3,"levelMultiplier":1,"hpMultiplier":4.79,"atkMultiplier":2.64,"defMultiplier":2.14,"speedMultiplier":1.43},{"heroId":13,"slot":4,"levelMultiplier":1,"hpMultiplier":4.79,"atkMultiplier":2.64,"defMultiplier":2.14,"speedMultiplier":1.43},{"heroId":10,"slot":5,"levelMultiplier":1,"hpMultiplier":4.79,"atkMultiplier":2.64,"defMultiplier":2.14,"speedMultiplier":1.43}]', '{"exp":644,"gold":969,"diamond":0}', '{"chapterName":"🚇 地下交通網","stageName":"隧道深處","description":"軌道上的回聲讓人分不清方向","bgTheme":"underground","difficulty":51,"recommendedLevel":63,"isBoss":false,"chapterIcon":"🚇"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('7-4', 7, 4, '[{"heroId":10,"slot":1,"levelMultiplier":1,"hpMultiplier":4.93,"atkMultiplier":2.71,"defMultiplier":2.21,"speedMultiplier":1.43},{"heroId":11,"slot":2,"levelMultiplier":1,"hpMultiplier":4.93,"atkMultiplier":2.71,"defMultiplier":2.21,"speedMultiplier":1.43},{"heroId":12,"slot":3,"levelMultiplier":1,"hpMultiplier":4.93,"atkMultiplier":2.71,"defMultiplier":2.21,"speedMultiplier":1.43},{"heroId":13,"slot":4,"levelMultiplier":1,"hpMultiplier":4.93,"atkMultiplier":2.71,"defMultiplier":2.21,"speedMultiplier":1.43},{"heroId":10,"slot":5,"levelMultiplier":1,"hpMultiplier":4.93,"atkMultiplier":2.71,"defMultiplier":2.21,"speedMultiplier":1.43}]', '{"exp":656,"gold":987,"diamond":0}', '{"chapterName":"🚇 地下交通網","stageName":"地下商場","description":"霓虹燈殘光映照著遊蕩的身影","bgTheme":"underground","difficulty":52,"recommendedLevel":64,"isBoss":false,"chapterIcon":"🚇"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('7-5', 7, 5, '[{"heroId":10,"slot":1,"levelMultiplier":1,"hpMultiplier":5.07,"atkMultiplier":2.79,"defMultiplier":2.29,"speedMultiplier":1.43},{"heroId":11,"slot":2,"levelMultiplier":1,"hpMultiplier":5.07,"atkMultiplier":2.79,"defMultiplier":2.29,"speedMultiplier":1.43},{"heroId":12,"slot":3,"levelMultiplier":1,"hpMultiplier":5.07,"atkMultiplier":2.79,"defMultiplier":2.29,"speedMultiplier":1.43},{"heroId":13,"slot":4,"levelMultiplier":1,"hpMultiplier":5.07,"atkMultiplier":2.79,"defMultiplier":2.29,"speedMultiplier":1.43},{"heroId":10,"slot":5,"levelMultiplier":1,"hpMultiplier":5.07,"atkMultiplier":2.79,"defMultiplier":2.29,"speedMultiplier":1.43}]', '{"exp":668,"gold":1004,"diamond":0}', '{"chapterName":"🚇 地下交通網","stageName":"維修通道","description":"狹窄通道中只能單列前進作戰","bgTheme":"underground","difficulty":53,"recommendedLevel":66,"isBoss":false,"chapterIcon":"🚇"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('7-6', 7, 6, '[{"heroId":10,"slot":1,"levelMultiplier":1,"hpMultiplier":5.21,"atkMultiplier":2.86,"defMultiplier":2.36,"speedMultiplier":1.43},{"heroId":11,"slot":2,"levelMultiplier":1,"hpMultiplier":5.21,"atkMultiplier":2.86,"defMultiplier":2.36,"speedMultiplier":1.43},{"heroId":12,"slot":3,"levelMultiplier":1,"hpMultiplier":5.21,"atkMultiplier":2.86,"defMultiplier":2.36,"speedMultiplier":1.43},{"heroId":13,"slot":4,"levelMultiplier":1,"hpMultiplier":5.21,"atkMultiplier":2.86,"defMultiplier":2.36,"speedMultiplier":1.43},{"heroId":10,"slot":5,"levelMultiplier":1,"hpMultiplier":5.21,"atkMultiplier":2.86,"defMultiplier":2.36,"speedMultiplier":1.43}]', '{"exp":680,"gold":1022,"diamond":0}', '{"chapterName":"🚇 地下交通網","stageName":"控制室","description":"監控螢幕仍播放著末日的畫面","bgTheme":"underground","difficulty":54,"recommendedLevel":67,"isBoss":false,"chapterIcon":"🚇"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('7-7', 7, 7, '[{"heroId":10,"slot":1,"levelMultiplier":1,"hpMultiplier":5.36,"atkMultiplier":2.93,"defMultiplier":2.43,"speedMultiplier":1.43},{"heroId":11,"slot":2,"levelMultiplier":1,"hpMultiplier":5.36,"atkMultiplier":2.93,"defMultiplier":2.43,"speedMultiplier":1.43},{"heroId":12,"slot":3,"levelMultiplier":1,"hpMultiplier":5.36,"atkMultiplier":2.93,"defMultiplier":2.43,"speedMultiplier":1.43},{"heroId":13,"slot":4,"levelMultiplier":1,"hpMultiplier":5.36,"atkMultiplier":2.93,"defMultiplier":2.43,"speedMultiplier":1.43},{"heroId":10,"slot":5,"levelMultiplier":1,"hpMultiplier":5.36,"atkMultiplier":2.93,"defMultiplier":2.43,"speedMultiplier":1.43},{"heroId":11,"slot":6,"levelMultiplier":1,"hpMultiplier":5.36,"atkMultiplier":2.93,"defMultiplier":2.43,"speedMultiplier":1.43}]', '{"exp":692,"gold":1040,"diamond":0}', '{"chapterName":"🚇 地下交通網","stageName":"秘密實驗區","description":"政府隱藏在地下的禁忌實驗室","bgTheme":"underground","difficulty":55,"recommendedLevel":68,"isBoss":false,"chapterIcon":"🚇"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('7-8', 7, 8, '[{"heroId":10,"slot":1,"levelMultiplier":1,"hpMultiplier":5.5,"atkMultiplier":3,"defMultiplier":2.5,"speedMultiplier":1.43},{"heroId":11,"slot":2,"levelMultiplier":1,"hpMultiplier":5.5,"atkMultiplier":3,"defMultiplier":2.5,"speedMultiplier":1.43},{"heroId":12,"slot":3,"levelMultiplier":1,"hpMultiplier":5.5,"atkMultiplier":3,"defMultiplier":2.5,"speedMultiplier":1.43},{"heroId":13,"slot":4,"levelMultiplier":1,"hpMultiplier":5.5,"atkMultiplier":3,"defMultiplier":2.5,"speedMultiplier":1.43},{"heroId":10,"slot":5,"levelMultiplier":1,"hpMultiplier":5.5,"atkMultiplier":3,"defMultiplier":2.5,"speedMultiplier":1.43},{"heroId":11,"slot":6,"levelMultiplier":1,"hpMultiplier":8.25,"atkMultiplier":4.5,"defMultiplier":3.75,"speedMultiplier":1.29}]', '{"exp":704,"gold":1058,"diamond":50,"items":[{"itemId":"chest_gold","quantity":1,"dropRate":1}]}', '{"chapterName":"🚇 地下交通網","stageName":"隧道之王","description":"統治整個地下世界的巨型變異體","bgTheme":"underground","difficulty":56,"recommendedLevel":70,"isBoss":true,"chapterIcon":"🚇"}');

-- ═══════════════════════════════════════════════════════════
-- 第 8 章 🌋 末日核心
-- ═══════════════════════════════════════════════════════════

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('8-1', 8, 1, '[{"heroId":11,"slot":1,"levelMultiplier":1,"hpMultiplier":5.5,"atkMultiplier":3,"defMultiplier":2.5,"speedMultiplier":1.5},{"heroId":12,"slot":2,"levelMultiplier":1,"hpMultiplier":5.5,"atkMultiplier":3,"defMultiplier":2.5,"speedMultiplier":1.5},{"heroId":13,"slot":3,"levelMultiplier":1,"hpMultiplier":5.5,"atkMultiplier":3,"defMultiplier":2.5,"speedMultiplier":1.5},{"heroId":14,"slot":4,"levelMultiplier":1,"hpMultiplier":5.5,"atkMultiplier":3,"defMultiplier":2.5,"speedMultiplier":1.5},{"heroId":11,"slot":5,"levelMultiplier":1,"hpMultiplier":5.5,"atkMultiplier":3,"defMultiplier":2.5,"speedMultiplier":1.5}]', '{"exp":716,"gold":1076,"diamond":0}', '{"chapterName":"🌋 末日核心","stageName":"外圍防線","description":"最後防線的殘骸訴說著絕望戰役","bgTheme":"core","difficulty":57,"recommendedLevel":71,"isBoss":false,"chapterIcon":"🌋"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('8-2', 8, 2, '[{"heroId":11,"slot":1,"levelMultiplier":1,"hpMultiplier":5.71,"atkMultiplier":3.14,"defMultiplier":2.57,"speedMultiplier":1.5},{"heroId":12,"slot":2,"levelMultiplier":1,"hpMultiplier":5.71,"atkMultiplier":3.14,"defMultiplier":2.57,"speedMultiplier":1.5},{"heroId":13,"slot":3,"levelMultiplier":1,"hpMultiplier":5.71,"atkMultiplier":3.14,"defMultiplier":2.57,"speedMultiplier":1.5},{"heroId":14,"slot":4,"levelMultiplier":1,"hpMultiplier":5.71,"atkMultiplier":3.14,"defMultiplier":2.57,"speedMultiplier":1.5},{"heroId":11,"slot":5,"levelMultiplier":1,"hpMultiplier":5.71,"atkMultiplier":3.14,"defMultiplier":2.57,"speedMultiplier":1.5}]', '{"exp":728,"gold":1093,"diamond":0}', '{"chapterName":"🌋 末日核心","stageName":"生物培養艙","description":"培養液中漂浮著不完整的人形","bgTheme":"core","difficulty":58,"recommendedLevel":72,"isBoss":false,"chapterIcon":"🌋"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('8-3', 8, 3, '[{"heroId":11,"slot":1,"levelMultiplier":1,"hpMultiplier":5.93,"atkMultiplier":3.29,"defMultiplier":2.64,"speedMultiplier":1.5},{"heroId":12,"slot":2,"levelMultiplier":1,"hpMultiplier":5.93,"atkMultiplier":3.29,"defMultiplier":2.64,"speedMultiplier":1.5},{"heroId":13,"slot":3,"levelMultiplier":1,"hpMultiplier":5.93,"atkMultiplier":3.29,"defMultiplier":2.64,"speedMultiplier":1.5},{"heroId":14,"slot":4,"levelMultiplier":1,"hpMultiplier":5.93,"atkMultiplier":3.29,"defMultiplier":2.64,"speedMultiplier":1.5},{"heroId":11,"slot":5,"levelMultiplier":1,"hpMultiplier":5.93,"atkMultiplier":3.29,"defMultiplier":2.64,"speedMultiplier":1.5}]', '{"exp":740,"gold":1111,"diamond":0}', '{"chapterName":"🌋 末日核心","stageName":"武器庫","description":"末日前的秘密武器仍完好如初","bgTheme":"core","difficulty":59,"recommendedLevel":73,"isBoss":false,"chapterIcon":"🌋"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('8-4', 8, 4, '[{"heroId":11,"slot":1,"levelMultiplier":1,"hpMultiplier":6.14,"atkMultiplier":3.43,"defMultiplier":2.71,"speedMultiplier":1.5},{"heroId":12,"slot":2,"levelMultiplier":1,"hpMultiplier":6.14,"atkMultiplier":3.43,"defMultiplier":2.71,"speedMultiplier":1.5},{"heroId":13,"slot":3,"levelMultiplier":1,"hpMultiplier":6.14,"atkMultiplier":3.43,"defMultiplier":2.71,"speedMultiplier":1.5},{"heroId":14,"slot":4,"levelMultiplier":1,"hpMultiplier":6.14,"atkMultiplier":3.43,"defMultiplier":2.71,"speedMultiplier":1.5},{"heroId":11,"slot":5,"levelMultiplier":1,"hpMultiplier":6.14,"atkMultiplier":3.43,"defMultiplier":2.71,"speedMultiplier":1.5},{"heroId":12,"slot":6,"levelMultiplier":1,"hpMultiplier":6.14,"atkMultiplier":3.43,"defMultiplier":2.71,"speedMultiplier":1.5}]', '{"exp":752,"gold":1129,"diamond":0}', '{"chapterName":"🌋 末日核心","stageName":"反應爐走廊","description":"走廊盡頭散發著詭異的藍色光芒","bgTheme":"core","difficulty":60,"recommendedLevel":74,"isBoss":false,"chapterIcon":"🌋"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('8-5', 8, 5, '[{"heroId":11,"slot":1,"levelMultiplier":1,"hpMultiplier":6.36,"atkMultiplier":3.57,"defMultiplier":2.79,"speedMultiplier":1.5},{"heroId":12,"slot":2,"levelMultiplier":1,"hpMultiplier":6.36,"atkMultiplier":3.57,"defMultiplier":2.79,"speedMultiplier":1.5},{"heroId":13,"slot":3,"levelMultiplier":1,"hpMultiplier":6.36,"atkMultiplier":3.57,"defMultiplier":2.79,"speedMultiplier":1.5},{"heroId":14,"slot":4,"levelMultiplier":1,"hpMultiplier":6.36,"atkMultiplier":3.57,"defMultiplier":2.79,"speedMultiplier":1.5},{"heroId":11,"slot":5,"levelMultiplier":1,"hpMultiplier":6.36,"atkMultiplier":3.57,"defMultiplier":2.79,"speedMultiplier":1.5},{"heroId":12,"slot":6,"levelMultiplier":1,"hpMultiplier":6.36,"atkMultiplier":3.57,"defMultiplier":2.79,"speedMultiplier":1.5}]', '{"exp":764,"gold":1147,"diamond":0}', '{"chapterName":"🌋 末日核心","stageName":"指揮中心","description":"全球感染的指令從這裡發出","bgTheme":"core","difficulty":61,"recommendedLevel":76,"isBoss":false,"chapterIcon":"🌋"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('8-6', 8, 6, '[{"heroId":11,"slot":1,"levelMultiplier":1,"hpMultiplier":6.57,"atkMultiplier":3.71,"defMultiplier":2.86,"speedMultiplier":1.5},{"heroId":12,"slot":2,"levelMultiplier":1,"hpMultiplier":6.57,"atkMultiplier":3.71,"defMultiplier":2.86,"speedMultiplier":1.5},{"heroId":13,"slot":3,"levelMultiplier":1,"hpMultiplier":6.57,"atkMultiplier":3.71,"defMultiplier":2.86,"speedMultiplier":1.5},{"heroId":14,"slot":4,"levelMultiplier":1,"hpMultiplier":6.57,"atkMultiplier":3.71,"defMultiplier":2.86,"speedMultiplier":1.5},{"heroId":11,"slot":5,"levelMultiplier":1,"hpMultiplier":6.57,"atkMultiplier":3.71,"defMultiplier":2.86,"speedMultiplier":1.5},{"heroId":12,"slot":6,"levelMultiplier":1,"hpMultiplier":6.57,"atkMultiplier":3.71,"defMultiplier":2.86,"speedMultiplier":1.5}]', '{"exp":776,"gold":1164,"diamond":0}', '{"chapterName":"🌋 末日核心","stageName":"基因改造室","description":"改造失敗的實驗體在暗處蠕動","bgTheme":"core","difficulty":62,"recommendedLevel":77,"isBoss":false,"chapterIcon":"🌋"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('8-7', 8, 7, '[{"heroId":11,"slot":1,"levelMultiplier":1,"hpMultiplier":6.79,"atkMultiplier":3.86,"defMultiplier":2.93,"speedMultiplier":1.5},{"heroId":12,"slot":2,"levelMultiplier":1,"hpMultiplier":6.79,"atkMultiplier":3.86,"defMultiplier":2.93,"speedMultiplier":1.5},{"heroId":13,"slot":3,"levelMultiplier":1,"hpMultiplier":6.79,"atkMultiplier":3.86,"defMultiplier":2.93,"speedMultiplier":1.5},{"heroId":14,"slot":4,"levelMultiplier":1,"hpMultiplier":6.79,"atkMultiplier":3.86,"defMultiplier":2.93,"speedMultiplier":1.5},{"heroId":11,"slot":5,"levelMultiplier":1,"hpMultiplier":6.79,"atkMultiplier":3.86,"defMultiplier":2.93,"speedMultiplier":1.5},{"heroId":12,"slot":6,"levelMultiplier":1,"hpMultiplier":6.79,"atkMultiplier":3.86,"defMultiplier":2.93,"speedMultiplier":1.5}]', '{"exp":788,"gold":1182,"diamond":0}', '{"chapterName":"🌋 末日核心","stageName":"核心通道","description":"通往一切終結之處的最後走廊","bgTheme":"core","difficulty":63,"recommendedLevel":78,"isBoss":false,"chapterIcon":"🌋"}');

INSERT INTO stage_configs (stageId, chapter, stage, enemies, rewards, extra)
VALUES ('8-8', 8, 8, '[{"heroId":11,"slot":1,"levelMultiplier":1,"hpMultiplier":7,"atkMultiplier":4,"defMultiplier":3,"speedMultiplier":1.5},{"heroId":12,"slot":2,"levelMultiplier":1,"hpMultiplier":7,"atkMultiplier":4,"defMultiplier":3,"speedMultiplier":1.5},{"heroId":13,"slot":3,"levelMultiplier":1,"hpMultiplier":7,"atkMultiplier":4,"defMultiplier":3,"speedMultiplier":1.5},{"heroId":14,"slot":4,"levelMultiplier":1,"hpMultiplier":7,"atkMultiplier":4,"defMultiplier":3,"speedMultiplier":1.5},{"heroId":11,"slot":5,"levelMultiplier":1,"hpMultiplier":7,"atkMultiplier":4,"defMultiplier":3,"speedMultiplier":1.5},{"heroId":12,"slot":6,"levelMultiplier":1,"hpMultiplier":10.5,"atkMultiplier":6,"defMultiplier":4.5,"speedMultiplier":1.35}]', '{"exp":800,"gold":1200,"diamond":50,"items":[{"itemId":"chest_gold","quantity":1,"dropRate":1}]}', '{"chapterName":"🌋 末日核心","stageName":"末日審判者","description":"感染源頭的最終存在等待著挑戰者","bgTheme":"core","difficulty":64,"recommendedLevel":80,"isBoss":true,"chapterIcon":"🌋"}');
